substitutions:
  name: boneio-32-l-07-73be28
  friendly_name: BoneIO ESP 32x10 Lights 73be28
  serial_prefix: esp   #Don't change it.

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: boneio.32x10-lights
    version: '0.7'

esp32:
  board: nodemcu-32s

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

udp:

packet_transport:
  - id: transport
    platform: udp
    update_interval: 5s
    encryption: 'BKL_BONEIO1_KEY' #set it to yours shared secret key
    rolling_code_enable: true
    binary_sensors:
      - in_s1_c
      - in_s1_d
    providers:
      - name: boneio-dr-8ch-03-30f8d8
        encryption: 'BKL_BONEIO2_KEY' #set it to yours shared secret key

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-32x10_lights_v0_7.yaml@latest
  import_full_config: true

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.6.0
    files: [devices/buzzer.yaml, devices/serial_no.yaml, devices_v0_7/display.yaml,
            devices_v0_7/i2c.yaml, devices_v0_7-v0_9/ina219.yaml, devices_v0_7-v0_9/lm75b.yaml,
            devices_v0_7-v0_9/pcf.yaml, boards/output/out01_02.yaml, boards/output/out03_04.yaml,
            boards/output/out05_06.yaml, boards/output/out07_08.yaml, boards/output/out09_10.yaml,
            boards/output/out11_12.yaml, boards/output/out13_14.yaml, boards/output/out15_16.yaml,
            boards/output/out17_18.yaml, boards/output/out19_20.yaml, boards/output/out21_22.yaml,
            boards/output/out23_24.yaml, boards/output/out25_26.yaml, boards/output/out27_28.yaml,
            boards/output/out29_30.yaml, boards/output/out31_32.yaml]

logger:
api:
  reboot_timeout: 0s
ota:
  - platform: esphome

web_server:
  port: 80
  local: true
  version: 3

time:
  - platform: homeassistant
    timezone: Europe/Warsaw
    id: homeassistant_time

globals:
  - id: states
    type: int[3]

script:
  - id: changeLightsState
    parameters:
      index: int
      lightA: light::LightState*
      lightB: light::LightState*
    then:
      - lambda: |-
          switch (id(states)[index]) {
              case 0: // LA(on), LB(off)  
                lightA->turn_on().perform();
                lightB->turn_off().perform();
                break;
              case 1: // LA(off), LB(on)
                lightA->turn_off().perform();
                lightB->turn_on().perform();
                break;
              case 2: // L1(on), L2(on)
                lightA->turn_on().perform();
                lightB->turn_on().perform();
                break;
            }

          id(states)[index] = (id(states)[index] + 1) % 3;
  - id: offLights
    parameters:
      index: int
      lightA: light::LightState*
      lightB: light::LightState*
    then:
      - lambda: |-
          id(states)[index] = 0;
          lightA->turn_off().perform();
          lightB->turn_off().perform();

light:
  - platform: binary
    name: Light 01
    output: out_01
    id: light_01
  - platform: binary
    name: Light 02
    output: out_02
    id: light_02
  - platform: binary
    name: Light 03
    output: out_03
    id: light_03
  - platform: binary
    name: Light 04
    output: out_04
    id: light_04
  - platform: binary
    name: Light 05
    output: out_05
    id: light_05
  - platform: binary
    name: Light 06
    output: out_06
    id: light_06
  - platform: binary
    name: Light 07
    output: out_07
    id: light_07
  - platform: binary
    name: Light 08
    output: out_08
    id: light_08
  - platform: binary
    name: Light 09
    output: out_09
    id: light_09
  - platform: binary
    name: Light 10
    output: out_10
    id: light_10
  - platform: binary
    name: Light 11
    output: out_11
    id: light_11
  - platform: binary
    name: Light 12
    output: out_12
    id: light_12
  - platform: binary
    name: Light 13
    output: out_13
    id: light_13
  - platform: binary
    name: Light 14
    output: out_14
    id: light_14
  - platform: binary
    name: Light 15
    output: out_15
    id: light_15
  - platform: binary
    name: Light 16
    output: out_16
    id: light_16
  - platform: binary
    name: Light 17
    output: out_17
    id: light_17
  - platform: binary
    name: Light 18
    output: out_18
    id: light_18
  - platform: binary
    name: Light 19
    output: out_19
    id: light_19
  - platform: binary
    name: Light 20
    output: out_20
    id: light_20
  - platform: binary
    name: Light 21
    output: out_21
    id: light_21
  - platform: binary
    name: Light 22
    output: out_22
    id: light_22
  - platform: binary
    name: Light 23
    output: out_23
    id: light_23
  - platform: binary
    name: Light 24
    output: out_24
    id: light_24
  - platform: binary
    name: Light 25
    output: out_25
    id: light_25
  - platform: binary
    name: Light 26
    output: out_26
    id: light_26
  - platform: binary
    name: Light 27
    output: out_27
    id: light_27
  - platform: binary
    name: Light 28
    output: out_28
    id: light_28
  - platform: binary
    name: Light 29
    output: out_29
    id: light_29
  - platform: binary
    name: Light 30
    output: out_30
    id: light_30
  - platform: binary
    name: Light 31
    output: out_31
    id: light_31
  - platform: binary
    name: Light 32
    output: out_32
    id: light_32

binary_sensor:
  - platform: gpio
    name: S1_A
    id: in_s1_a
    pin:
      pcf8574: pcf_inputs_1to14
      number: 0
      mode:
        input: true
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 0.4s
          - OFF for at least 0.1s
        then:
          - script.execute:
              id: changeLightsState
              index: 0
              lightA: !lambda 'return id(light_01);'
              lightB: !lambda 'return id(light_02);'
        invalid_cooldown: 0.5s
      - timing:
          - ON for at least 0.7s
        then:
          - script.execute:
              id: offLights
              index: 0
              lightA: !lambda 'return id(light_01);'
              lightB: !lambda 'return id(light_02);'
        invalid_cooldown: 0.5s

  - platform: gpio
    name: S1_B
    id: in_s1_b
    pin:
      pcf8574: pcf_inputs_1to14
      number: 1
      mode:
        input: true
      inverted: true
    on_multi_click:
      - timing:
          - ON for at most 0.4s
          - OFF for at least 0.1s
        then:
          - script.execute:
              id: changeLightsState
              index: 1
              lightA: !lambda 'return id(light_03);'
              lightB: !lambda 'return id(light_04);'
        invalid_cooldown: 0.5s
      - timing:
          - ON for at least 0.7s
        then:
          - script.execute:
              id: offLights
              index: 1
              lightA: !lambda 'return id(light_03);'
              lightB: !lambda 'return id(light_04);'
        invalid_cooldown: 0.5s

  - platform: gpio
    name: S1_C
    id: in_s1_c
    pin:
      pcf8574: pcf_inputs_1to14
      number: 2
      mode:
        input: true
      inverted: true
    # on_press:
    #   then:
    #   - light.toggle: light_03

  - platform: gpio
    name: S1_D
    id: in_s1_d
    pin:
      pcf8574: pcf_inputs_1to14
      number: 3
      mode:
        input: true
      inverted: true
    # on_press:
    #   then:
    #   - light.toggle: light_04

  - platform: gpio
    name: S2_A
    id: in_s2_a
    pin:
      pcf8574: pcf_inputs_1to14
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_05

  - platform: gpio
    name: S2_B
    id: in_s2_b
    pin:
      pcf8574: pcf_inputs_1to14
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_06

  - platform: gpio
    name: S2_C
    id: in_s2_c
    pin:
      pcf8574: pcf_inputs_1to14
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_07

  - platform: gpio
    name: S2_D
    id: in_s2_d
    pin:
      pcf8574: pcf_inputs_1to14
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_08

  - platform: gpio
    name: S3_A
    id: in_s3_a
    pin:
      pcf8574: pcf_inputs_1to14
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_09

  - platform: gpio
    name: S3_B
    id: in_s3_b
    pin:
      pcf8574: pcf_inputs_1to14
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_10

  - platform: gpio
    name: S3_C
    id: in_s3_c
    pin:
      pcf8574: pcf_inputs_1to14
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_11

  - platform: gpio
    name: S3_D
    id: in_s3_d
    pin:
      pcf8574: pcf_inputs_1to14
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_12

  - platform: gpio
    name: IN_13
    id: in_13
    pin:
      pcf8574: pcf_inputs_1to14
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_13

  - platform: gpio
    name: IN_14
    id: in_14
    pin:
      pcf8574: pcf_inputs_1to14
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_14

  - platform: gpio
    name: IN_15
    id: in_15
    pin:
      pcf8574: pcf_inputs_15to28
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_15

  - platform: gpio
    name: IN_16
    id: in_16
    pin:
      pcf8574: pcf_inputs_15to28
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_16

  - platform: gpio
    name: IN_17
    id: in_17
    pin:
      pcf8574: pcf_inputs_15to28
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_17

  - platform: gpio
    name: IN_18
    id: in_18
    pin:
      pcf8574: pcf_inputs_15to28
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_18

  - platform: gpio
    name: IN_19
    id: in_19
    pin:
      pcf8574: pcf_inputs_15to28
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_19

  - platform: gpio
    name: IN_20
    id: in_20
    pin:
      pcf8574: pcf_inputs_15to28
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_20

  - platform: gpio
    name: IN_21
    id: in_21
    pin:
      pcf8574: pcf_inputs_15to28
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_21

  - platform: gpio
    name: IN_22
    id: in_22
    pin:
      pcf8574: pcf_inputs_15to28
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_22

  - platform: gpio
    name: IN_23
    id: in_23
    pin:
      pcf8574: pcf_inputs_15to28
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_23

  - platform: gpio
    name: IN_24
    id: in_24
    pin:
      pcf8574: pcf_inputs_15to28
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_24

  - platform: gpio
    name: IN_25
    id: in_25
    pin:
      pcf8574: pcf_inputs_15to28
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_25

  - platform: gpio
    name: IN_26
    id: in_26
    pin:
      pcf8574: pcf_inputs_15to28
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_26

  - platform: gpio
    name: IN_27
    id: in_27
    pin:
      pcf8574: pcf_inputs_15to28
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_27

  - platform: gpio
    name: IN_28
    id: in_28
    pin:
      pcf8574: pcf_inputs_15to28
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_28

  - platform: gpio
    name: IN_29
    id: in_29
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_29

  - platform: gpio
    name: IN_30
    id: in_30
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_30

  - platform: gpio
    name: IN_31
    id: in_31
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_31

  - platform: gpio
    name: IN_32
    id: in_32
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - light.toggle: light_32

  - platform: gpio
    name: IN_33
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 4
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: IN_34
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 5
      mode:
        input: true
      inverted: true

  - platform: gpio
    name: IN_35
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 6
      mode:
        input: true
      inverted: true

#######################
### 1 Wire SECTION  ###
#######################
one_wire:
  - platform: gpio
    pin: GPIO32

######################
### MODBUS SECTION ###
######################
# UNCOMMENT BELOW TO USE MODBUS
uart:
  id: uart_pin14_15
  rx_pin: GPIO14
  tx_pin: GPIO15
  baud_rate: 9600
  stop_bits: 1


sensor:
  - platform: dallas_temp
    address: 0x1f07237002c46028
    name: "Room 1"

  - platform: dallas_temp
    address: 0x110823a1af6e8228
    name: "Room 2"

  - platform: sdm_meter
    address: 0x01
    phase_a:
      current:
        name: "SDM120M Current"
      voltage:
        name: "SDM230M Voltage"
      active_power:
        name: "SDM230M Power"

# modbus:
#   send_wait_time: 200ms
#   uart_id: uart_pin14_15
#   id: boneio_modbus

# modbus_controller:
#   - id: sdm120m
#     address: 0x01
#     modbus_id: boneio_modbus
#     setup_priority: -10
#     update_interval: 60s
