## Gabinet / Sypialnia / Komunikacja
substitutions:
  name: boneio-dr-8ch-03-7d86e0
  friendly_name: 'BoneIO Dimmer LED 7d86e0'
  serial_prefix: 'dim' #Don't change it.

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  name_add_mac_suffix: false
  project:
    name: boneio.dimmer-led
    version: '0.3'
  on_boot:
    - priority: 600
      then:
        - lambda: |-
            id(led_state_hall).publish_state("OFF");

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://boneIO-eu/esphome-LM75@main #Original source and thank you note for BTomala https://github.com/boneIO-eu/esphome-lm75
    components: [lm75]

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.7.1
    files:
      [
        'devices/serial_no.yaml',
        'devices/dimmer_i2c.yaml',
        'devices/dimmer_ina219.yaml',
        'boards/dimmer_output.yaml',
      ]

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16

udp:

packet_transport:
  - id: transport
    platform: udp
    update_interval: 30s
    providers:
      - name: boneio-32-l-07-39d104
        encryption: 'JAG_BONEIO1_KEY' #set it to yours shared secret key

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-dimmer_8ch-v0_3.yaml@latest
  import_full_config: true

pcf8574:
  - id: 'pcf_inputs'
    address: 0x38

logger:
  level: INFO
api:
  reboot_timeout: 0s
ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
  local: true
  version: 3

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw
    servers:
      - ntp1.tp.pl
      - ntp2.tp.pl

text_sensor:
  - platform: version
    name: 'boneio-dimmer- Version'
    icon: mdi:cube-outline
    entity_category: diagnostic
  - platform: ethernet_info
    ip_address:
      entity_category: diagnostic
      name: boneio-dimmer IP
  - platform: template
    name: 'Hostname'
    id: hostname
    entity_category: diagnostic
    lambda: |-
      return std::string(id(eth).get_use_address());
    update_interval: 5min
  - platform: template
    name: "Led state"
    id: led_state_hall

script:
###### PRZEDPOKOJ ##############################################
  - id: przedpokoj
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("przedpokoj", "%s %s", sn.c_str(), pt.c_str());
          
          auto led_state = id(led_state_hall).state;
          ESP_LOGI("przedpokoj", "%s", led_state.c_str());
          
          if (pt != "OP") {
            return;
          }
          
          if (sn == "CO") {
            if (led_state == "OFF") {
              id(turn_on_led_hall)->execute(0.15);
              id(led_state_hall).publish_state("ON_15");
              id(turn_off_led_hall_after)->execute(90);
            } else if (led_state == "ON_15") {
              id(turn_off_led_hall_after)->execute(90);
            }
          }
          
          if (sn == "SW") {
            if (led_state == "OFF" || led_state == "ON_15") {
              id(turn_off_led_hall_after)->stop();
              id(turn_on_led_hall)->execute(1.);
              id(led_state_hall).publish_state("ON_100");
              id(turn_off_led_hall_after)->execute(900);
            } else if (led_state == "ON_100") {
              id(turn_off_led_hall_after)->stop();
              id(turn_off_led_hall_after)->execute(0);
            }
          }

  - id: turn_on_led_hall
    parameters:
      brightness: float
    then:
      - lambda: |-
          ESP_LOGI("turn_on_led_hall", "set brightness %.2f", brightness);
          
          light::LightState* lights[] = { id(L09A), id(L09B), id(L10A), id(L10B)};
          
          for (auto *l : lights) {
            auto call = l->turn_on();
            call.set_brightness(brightness);
            call.perform();
          }

  - id: turn_off_led_hall_after
    mode: restart
    parameters:
      delay_s: int
    then:
      - lambda: |-
          ESP_LOGI("turn_off_led_hall_after", "%d off before delay", delay_s);
      - delay: !lambda return delay_s * 1000;
      - lambda: |-
          ESP_LOGI("turn_off_led_hall_after", "off");
          
          light::LightState* lights[] = { id(L09A), id(L09B), id(L10A), id(L10B)};
          for (auto *l : lights) {
            auto call = l->turn_off();
            call.perform();
          }
          id(led_state_hall).publish_state("OFF");

###### PRZEDPOKOJ ##############################################
###### GABINET ######
  - id: gabinet
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("gabinet", "%s %s", sn.c_str(), pt.c_str());
          
          // L11 -> led polka - Narazie nie obslugiwana
          // L12 -> led Blenda
          
          if (pt == "LP" || pt == "VLP") {
            id(L12).turn_off().perform();
          }
          
          if (sn == "S12_P" && pt == "SP") {
            id(L12).toggle().perform();
          }
###### GABINET #####
###### SYPIALNIA #####
  - id: sypialnia
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("sypialnia", "%s %s", sn.c_str(), pt.c_str());
          
          if (pt == "VLP") {
            id(L03).turn_off().perform();
            id(L04).turn_off().perform();
          }
          
          if ((sn == "S05_P" || sn == "S07_LG" || sn == "S07_LD"
                             || sn == "S06_PG" || sn == "S06_PD") && pt == "LP") {
            id(L03).turn_off().perform();
            id(L04).turn_off().perform();
          }
          
          if (sn == "S05_P" && pt == "SP") {
            auto isLedOn = id(L03).current_values.is_on() && id(L04).current_values.is_on();
            if (isLedOn) {
              id(L03).turn_off().perform();
              id(L04).turn_off().perform();
            } else {
              id(L03).turn_on().perform();
              id(L04).turn_on().perform();
            }
          }
          
          //L03
          if ((sn == "S07_LG" || sn == "S06_PG") && pt == "SP") {
            id(L03).toggle().perform();
          }
          
          //L04
          if ((sn == "S07_LD" || sn == "S06_PD") && pt == "SP") {
            id(L04).toggle().perform();
          }

###### SYPIALNIA #####
##### ALL ############
  - id: master_off
    mode: single
    then:
      - lambda: |-
          ESP_LOGI("master_off", "start");
          
          light::LightState* lights[] = 
            { id(L03), id(L04), id(L11), id(L12),
              id(L09A), id(L09B), id(L10A), id(L10B)};
          
          for (auto *l : lights) {
            auto call = l->turn_off();
            call.perform();
          }
          
          ESP_LOGI("master_off", "end");
##### ALL ############

binary_sensor:
######### PRZEDPOKOJ #######################################
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S10
    remote_id: S10
    type: data
    on_press:
      then:
        - logger.log: "R S10 OP -> przedpokoj sypialnia/salon"
        - script.execute:
            id: przedpokoj
            sn: "SW"
            pt: "OP"
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S11_L
    remote_id: S11_L
    type: data
    on_multi_click:
      - timing:
          - ON for at least 3s
        then:
          - logger.log: "S11_L VLP -> przedpokoj wejscie lewa"
          - script.execute:
              id: master_off
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "R S11_L OP -> przedpokoj wejscie lewa"
          - script.execute:
              id: przedpokoj
              sn: "SW"
              pt: "OP"

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S09_D
    remote_id: S09_D
    type: data
    on_press:
      then:
        - logger.log: "R S09_D OP -> przedpokoj sypialnia/salon"
        - script.execute:
            id: przedpokoj
            sn: "SW"
            pt: "OP"
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_CO_1
    remote_id: CO_1
    type: data
    on_press:
      then:
        - logger.log: "CO_1 OP Czujnik obecnosci"
        - script.execute:
            id: przedpokoj
            sn: "CO"
            pt: "OP"
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_CO_2
    remote_id: CO_2
    type: data
    on_press:
      then:
        - logger.log: "CO_2 OP Czujnik obecnosci"
        - script.execute:
            id: przedpokoj
            sn: "CO"
            pt: "OP"
######### PRZEDPOKJ #######################################
######### GABINET    #######################################
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S12_P
    remote_id: S12_P
    type: data
    on_multi_click: !include { file: on-multi-click.yaml, vars: { switch_name: "S12_P", script: "gabinet" } }

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S12_L
    remote_id: S12_L
    type: data
    on_multi_click: !include { file: on-multi-click.yaml, vars: { switch_name: "S12_L", script: "gabinet" } }

######### GABINET    #######################################
######### SYPIALNIA  #######################################
  # S05_L S05_P
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S05_L
    remote_id: S05_L
    type: data
    on_multi_click: !include { file: on-multi-click.yaml, vars: { switch_name: "S05_L", script: "sypialnia" } }

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S05_P
    remote_id: S05_P
    type: data
    on_multi_click: !include { file: on-multi-click.yaml, vars: { switch_name: "S05_P", script: "sypialnia" } }

  # S06_LG S06_LD S06_PG S06_PD
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S06_LG
    remote_id: S06_LG
    type: data
    on_multi_click: !include { file: on-multi-click.yaml, vars: { switch_name: "S06_LG", script: "sypialnia" } }

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S06_LD
    remote_id: S06_LD
    type: data
    on_multi_click: !include { file: on-multi-click.yaml, vars: { switch_name: "S06_LD", script: "sypialnia" } }

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S06_PG
    remote_id: S06_PG
    type: data
    on_multi_click: !include { file: on-multi-click.yaml, vars: { switch_name: "S06_PG", script: "sypialnia" } }

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S06_PD
    remote_id: S06_PD
    type: data
    on_multi_click: !include { file: on-multi-click.yaml, vars: { switch_name: "S06_PD", script: "sypialnia" } }

  # S07_LG S07_LD S07_PG S07_PD
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S07_LG
    remote_id: S07_LG
    type: data
    on_multi_click: !include { file: on-multi-click.yaml, vars: { switch_name: "S07_LG", script: "sypialnia" } }

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S07_LD
    remote_id: S07_LD
    type: data
    on_multi_click: !include { file: on-multi-click.yaml, vars: { switch_name: "S07_LD", script: "sypialnia" } }

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S07_PG
    remote_id: S07_PG
    type: data
    on_multi_click: !include { file: on-multi-click.yaml, vars: { switch_name: "S07_PG", script: "sypialnia" } }

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S07_PD
    remote_id: S07_PD
    type: data
    on_multi_click: !include { file: on-multi-click.yaml, vars: { switch_name: "S07_PD", script: "sypialnia" } }

######### SYPIALNIA  #######################################

light:
  - platform: monochromatic
    output: chl01
    name: 'L03 - Blenda sypialnia'
    id: L03
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chl02
    name: 'L04 - Lozko sypialnia'
    id: L04
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chl03
    name: 'L11 - Gabinet polka'
    id: L11
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chl04
    name: 'L12 - Gabinet blenda'
    id: L12
    default_transition_length: 2s
    gamma_correct: 0

  - platform: monochromatic
    output: chr01
    name: 'L09A'
    id: L09A
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr02
    name: 'L09B'
    id: L09B
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr03
    name: 'L10A'
    id: L10A
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr04
    name: 'L10B'
    id: L10B
    default_transition_length: 2s
    gamma_correct: 0

sensor:
  - platform: lm75
    id: boneIO_temp
    name: 'Temperature'
    update_interval: 30s
    entity_category: diagnostic
    on_value_range:
      - above: 70.0
        then:
          - switch.turn_on: buzzer
      - below: 70.0
        then:
          - switch.turn_off: buzzer

switch:
  - platform: gpio
    id: buzzer
    name: 'Buzzer'
    pin:
      pcf8574: pcf_inputs
      number: 0
      mode:
        output: true
      inverted: true