substitutions:
  name: boneio-dr-8ch-03-30f8d8
  friendly_name: 'BoneIO Dimmer LED 30f8d8'
  serial_prefix: 'dim' #Don't change it.

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  name_add_mac_suffix: false
  project:
    name: boneio.dimmer-led
    version: '0.3'

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://boneIO-eu/esphome-LM75@main #Original source and thank you note for BTomala https://github.com/boneIO-eu/esphome-lm75
    components: [lm75]

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.7.1
    files:
      [
        'devices/serial_no.yaml',
        'devices/dimmer_i2c.yaml',
        'devices/dimmer_ina219.yaml',
        'boards/dimmer_output.yaml',
      ]

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16

udp:

packet_transport:
  - id: transport
    platform: udp
    update_interval: 30s
    encryption: 'JAG_BONEIO2_KEY' #set it to yours shared secret key
    rolling_code_enable: false
    binary_sensors:
      - LED_STATE
    providers:
      - name: boneio-32-l-07-73be28
        encryption: 'JAG_BONEIO1_KEY' #set it to yours shared secret key

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-dimmer_8ch-v0_3.yaml@latest
  import_full_config: true

pcf8574:
  - id: 'pcf_inputs'
    address: 0x38

logger:
  level: VERBOSE
  logs:
    packet_transport: VERBOSE
    i2c.idf: INFO
    i2c: INFO
api:
  reboot_timeout: 0s
ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
  local: true
  version: 3

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw
    servers:
      - ntp1.tp.pl
      - ntp2.tp.pl

text_sensor:
  - platform: version
    name: 'boneio-dimmer- Version'
    icon: mdi:cube-outline
    entity_category: diagnostic
  - platform: ethernet_info
    ip_address:
      entity_category: diagnostic
      name: boneio-dimmer IP
  - platform: template
    name: 'Hostname'
    id: hostname
    entity_category: diagnostic
    lambda: |-
      return id(eth).get_use_address();
    update_interval: 5min

script:
  - id: przedpokuj
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("przedpokuj", "%s %s", sn.c_str(), pt.c_str());
          id(L09A).toggle().perform();
          id(L09B).toggle().perform();
          id(L10A).toggle().perform();
          id(L10B).toggle().perform();
  - id: test
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("test", "%s %s", sn.c_str(), pt.c_str());
          
          // L03 -> L1
          // L04 -> L2
          
          if ((sn == "TS3_A" && pt == "LP") || pt == "VLP") {
            id(L03).turn_off().perform();
            id(L04).turn_off().perform();
            id(LED_STATE).publish_state(false);
          }
          
          if (sn == "TS3_A" && pt == "SP") {
            auto isLedOn = id(L03).current_values.is_on() || id(L04).current_values.is_on();

            if (isLedOn) {
              id(L03).turn_off().perform();
              id(L04).turn_off().perform();
            } else {
              id(L03).turn_on().perform();
              id(L04).turn_on().perform();
            }
          
            id(LED_STATE).publish_state(!isLedOn);
          }

binary_sensor:
  - platform: template
    id: LED_STATE

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-73be28
    id: remote_S10
    remote_id: S10
    on_press:
      then:
        - logger.log: "R S10 OP -> przedpokoj sypialnia/salon"
        - script.execute:
            id: przedpokuj
            sn: "S10"
            pt: "OP"
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-73be28
    id: remote_S11_P
    remote_id: S11_P
    on_press:
      then:
        - logger.log: "R S11_P OP -> przedpokoj sypialnia/salon"
        - script.execute:
            id: przedpokuj
            sn: "S11_P"
            pt: "OP"
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-73be28
    id: remote_S09_D
    remote_id: S09_D
    on_press:
      then:
        - logger.log: "R S09_D OP -> przedpokoj sypialnia/salon"
        - script.execute:
            id: przedpokuj
            sn: "S09_D"
            pt: "OP"

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-73be28
    id: remote_TS3_A
    remote_id: TS3_A
    type: data
    on_multi_click:
      - timing:
          - ON for at least 3s
        then:
          - logger.log: "TS3_A VLP"
          - script.execute:
              id: test
              sn: "TS3_A"
              pt: "VLP"
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "TS3_A LP"
          - script.execute:
              id: test
              sn: "TS3_A"
              pt: "LP"
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "TS3_A SP"
          - script.execute:
              id: test
              sn: "TS3_A"
              pt: "SP"

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-73be28
    id: remote_TS3_B
    remote_id: TS3_B
    type: data
    on_multi_click:
      - timing:
          - ON for at least 3s
        then:
          - logger.log: "TS3_B VLP"
          - script.execute:
              id: test
              sn: "TS3_B"
              pt: "VLP"

light:
  - platform: monochromatic
    output: chl01
    name: 'L03'
    id: L03
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chl02
    name: 'L04'
    id: L04
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chl03
    name: 'L11'
    id: L11
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chl04
    name: 'L12'
    id: L12
    default_transition_length: 2s
    gamma_correct: 0

  - platform: monochromatic
    output: chr01
    name: 'L09A'
    id: L09A
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr02
    name: 'L09B'
    id: L09B
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr03
    name: 'L10A'
    id: L10A
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr04
    name: 'L10B'
    id: L10B
    default_transition_length: 2s
    gamma_correct: 0

sensor:
  - platform: lm75
    id: boneIO_temp
    name: 'Temperature'
    update_interval: 30s
    entity_category: diagnostic
    on_value_range:
      - above: 70.0
        then:
          - switch.turn_on: buzzer
      - below: 70.0
        then:
          - switch.turn_off: buzzer

switch:
  - platform: gpio
    id: buzzer
    name: 'Buzzer'
    pin:
      pcf8574: pcf_inputs
      number: 0
      mode:
        output: true
      inverted: true