substitutions:
  name: boneio-dr-8ch-03-7c8500
  friendly_name: 'BoneIO Dimmer LED 7c8500'
  serial_prefix: 'dim' #Don't change it.

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  name_add_mac_suffix: false
  project:
    name: boneio.dimmer-led
    version: '0.3'

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://boneIO-eu/esphome-LM75@main #Original source and thank you note for BTomala https://github.com/boneIO-eu/esphome-lm75
    components: [lm75]

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.7.1
    files:
      [
        'devices/serial_no.yaml',
        'devices/dimmer_i2c.yaml',
        'devices/dimmer_ina219.yaml',
        'boards/dimmer_output.yaml',
      ]

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16

udp:

packet_transport:
  - id: transport
    platform: udp
    providers:
      - name: boneio-32-l-07-39d104
        encryption: 'JAG_BONEIO1_KEY' #set it to yours shared secret key

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-dimmer_8ch-v0_3.yaml@latest
  import_full_config: true

pcf8574:
  - id: 'pcf_inputs'
    address: 0x38

logger:
api:
  reboot_timeout: 0s
ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
  local: true
  version: 3

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw
    servers:
      - ntp1.tp.pl
      - ntp2.tp.pl

text_sensor:
  - platform: version
    name: 'boneio-dimmer- Version'
    icon: mdi:cube-outline
    entity_category: diagnostic
  - platform: ethernet_info
    ip_address:
      entity_category: diagnostic
      name: boneio-dimmer IP
  - platform: template
    name: 'Hostname'
    id: hostname
    entity_category: diagnostic
    lambda: |-
      return id(eth).get_use_address();
    update_interval: 5min

script:
  - id: salon
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("salon", "%s %s", sn.c_str(), pt.c_str());
          
          // - SP -> L01:1;L2:0 -> SP -> L01:0;L02:1 -> SP -> L01:1; L02:1 -> SP ->
          //     |                    |                     |
          //     |->LP ->-------------|->LP ->--------------|->LP -> L01:0;L02:0
          //
          
          if (((sn == "S02B_P" || sn == "S03B_P") && pt == "LP") || pt == "VLP") {
            id(L01A).turn_off().perform();
            id(L01B).turn_off().perform();
            id(L02).turn_off().perform();
            return;
          }
          
          // handle SP
          if ((sn == "S02B_P" || sn == "S03B_P") && pt == "SP") {
            auto isOnL01 = id(L01A).current_values.is_on() || id(L01B).current_values.is_on();
            auto isOnL02 = id(L02).current_values.is_on();

            if ((!isOnL01 && !isOnL02) || (isOnL01 && isOnL02)) {
              id(L01A).turn_on().perform();
              id(L01B).turn_on().perform();
              id(L02).turn_off().perform();
            }

            if (isOnL01 && !isOnL02) {
              id(L01A).turn_off().perform();
              id(L01B).turn_off().perform();
              id(L02).turn_on().perform();
            }

            if (!isOnL01 && isOnL02) {
              id(L01A).turn_on().perform();
              id(L01B).turn_on().perform();
              id(L02).turn_on().perform();
            }
          }

  - id: lazienka
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("lazienka", "%s %s", sn.c_str(), pt.c_str());

binary_sensor:
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S02B_P
    remote_id: S02B_P
    type: data
    on_multi_click:
      - timing: #Very long push
          - ON for at least 3s
        then:
          - logger.log: "S02B_P VLP -> salon/wyspa"
          - script.execute:
              id: salon
              sn: "S02B_P"
              pt: "VLP"
      - timing: #Long push
          - ON for at least 1s
        then:
          - logger.log: "S02B_P LP -> salon/wyspa"
          - script.execute:
              id: salon
              sn: "S02B_P"
              pt: "LP"
      - timing: #Short push
          - ON for at most 1s   # Press less then 1 sek.
        then:
          - logger.log: "S02B_P SP -> salon/wyspa"
          - script.execute:
              id: salon
              sn: "S02B_P"
              pt: "SP"

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S03B_P
    remote_id: S03B_P
    type: data
    on_multi_click:
      - timing: #Very long push
          - ON for at least 3s
        then:
          - logger.log: "S02B_P VLP -> salon/wyspa"
          - script.execute:
              id: salon
              sn: "S03B_P"
              pt: "VLP"
      - timing: #Long push
          - ON for at least 1s #Press more then 1s
        then:
          - logger.log: "S03B_P LP -> salon/wyspa"
          - script.execute:
              id: salon
              sn: "S03B_P"
              pt: "LP"
      - timing: #Short push
          - ON for at most 1s   # Press less then 1 sek.
        then:
          - logger.log: "S03B_P SP -> salon/wyspa"
          - script.execute:
              id: salon
              sn: "S03B_P"
              pt: "SP"

light:
  # Lazienka
  - platform: monochromatic
    output: chl01
    name: 'L05 - Lazienka wanna'
    id: L05
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chl02
    name: 'L06 - Lazienka prysznic'
    id: L06
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chl03
    name: 'L07 - Lazienka szafka/lustro'
    id: L07
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chl04
    name: 'L08 - Lazienka wc'
    id: L08
    default_transition_length: 2s
    gamma_correct: 0

  # Salon
  - platform: monochromatic
    output: chr01
    name: 'L01A - Salon blenda prawa strona'
    id: L01A
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr02
    name: 'L01B - Salon blenda lewa strona'
    id: L01B
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr03
    name: 'L02 - Salon TV'
    id: L02
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr04
    name: 'X - Nie uzywane'
    id: L_not_use
    default_transition_length: 2s
    gamma_correct: 0

sensor:
  - platform: lm75
    id: boneIO_temp
    name: 'Temperature'
    update_interval: 30s
    entity_category: diagnostic
    on_value_range:
      - above: 70.0
        then:
          - switch.turn_on: buzzer
      - below: 70.0
        then:
          - switch.turn_off: buzzer

switch:
  - platform: gpio
    id: buzzer
    name: 'Buzzer'
    pin:
      pcf8574: pcf_inputs
      number: 0
      mode:
        output: true
      inverted: true