substitutions:
  name: boneio-dr-8ch-03-7d86e0
  friendly_name: 'BoneIO Dimmer LED 7d86e0'
  serial_prefix: 'dim' #Don't change it.

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  name_add_mac_suffix: false
  project:
    name: boneio.dimmer-led
    version: '0.3'

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://boneIO-eu/esphome-LM75@main #Original source and thank you note for BTomala https://github.com/boneIO-eu/esphome-lm75
    components: [lm75]

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.7.1
    files:
      [
        'devices/serial_no.yaml',
        'devices/dimmer_i2c.yaml',
        'devices/dimmer_ina219.yaml',
        'boards/dimmer_output.yaml',
      ]

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16

udp:

packet_transport:
  - id: transport
    platform: udp
    update_interval: 5s
    providers:
      - name: boneio-32-l-07-39d104
        encryption: 'JAG_BONEIO1_KEY' #set it to yours shared secret key

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-dimmer_8ch-v0_3.yaml@latest
  import_full_config: true

pcf8574:
  - id: 'pcf_inputs'
    address: 0x38

logger:
api:
  reboot_timeout: 0s
ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
  local: true
  version: 3

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw
    servers:
      - ntp1.tp.pl
      - ntp2.tp.pl

text_sensor:
  - platform: version
    name: 'boneio-dimmer- Version'
    icon: mdi:cube-outline
    entity_category: diagnostic
  - platform: ethernet_info
    ip_address:
      entity_category: diagnostic
      name: boneio-dimmer IP
  - platform: template
    name: 'Hostname'
    id: hostname
    entity_category: diagnostic
    lambda: |-
      return id(eth).get_use_address();
    update_interval: 5min

script:
  - id: przedpokoj
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("przedpokoj", "%s %s", sn.c_str(), pt.c_str());
          id(L09A).toggle().perform();
          id(L09B).toggle().perform();
          id(L10A).toggle().perform();
          id(L10B).toggle().perform();
  ###### GABINET #####
  - id: gabinet
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("gabinet", "%s %s", sn.c_str(), pt.c_str());
          
          // L11 -> led polka
          // L12 -> led Blenda
          
          if ((sn == "S12_P" && pt == "LP") || pt == "VLP") {
            id(L11).turn_off().perform();
            id(L12).turn_off().perform();
          }
          
          if (sn == "S12_P" && pt == "SP") {
            auto isOnL11 = id(L11).current_values.is_on();
            auto isOnL12 = id(L12).current_values.is_on();
            if ((!isOnL11 && !isOnL12) || (isOnL11 && isOnL12)) {
              id(L12).turn_on().perform();
              id(L11).turn_off().perform();
            }
          
            if (isOnL12 && !isOnL11) {
              id(L12).turn_off().perform();
              id(L11).turn_on().perform();
            }
          
            if (!isOnL12 && isOnL11) {
              id(L12).turn_on().perform();
              id(L11).turn_on().perform();
            }
          }
###### GABINET #####
###### SYPIALNIA #####
  - id: sypialnia
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("sypialnia", "%s %s", sn.c_str(), pt.c_str());

###### SYPIALNIA #####

binary_sensor:
######### PRZEDPOKOJ #######################################
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S10
    remote_id: S10
    type: data
    on_press:
      then:
        - logger.log: "R S10 OP -> przedpokoj sypialnia/salon"
        - script.execute:
            id: przedpokoj
            sn: "S10"
            pt: "OP"
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S11_P
    remote_id: S11_P
    type: data
    on_press:
      then:
        - logger.log: "R S11_P OP -> przedpokoj sypialnia/salon"
        - script.execute:
            id: przedpokoj
            sn: "S11_P"
            pt: "OP"
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S09_D
    remote_id: S09_D
    type: data
    on_press:
      then:
        - logger.log: "R S09_D OP -> przedpokoj sypialnia/salon"
        - script.execute:
            id: przedpokoj
            sn: "S09_D"
            pt: "OP"
######### PRZEDPOKJ #######################################
######### GABINET    #######################################
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S12_P
    remote_id: S12_P
    type: data
    on_multi_click:
      - timing:
          - ON for at least 3s
        then:
          - logger.log: "S12_P VLP -> gabinet Prawa"
          - script.execute:
              id: gabinet
              sn: "S12_P"
              pt: "VLP"
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "S12_P LP -> gabinet Prawa"
          - script.execute:
              id: gabinet
              sn: "S12_P"
              pt: "LP"
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "S12_P SP -> gabinet Prawa"
          - script.execute:
              id: gabinet
              sn: "S12_P"
              pt: "SP"
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S12_L
    remote_id: S12_L
    type: data
    on_multi_click:
      - timing:
          - ON for at least 3s
        then:
          - logger.log: "S12_L VLP -> gabinet Lewa"
          - script.execute:
              id: gabinet
              sn: "S12_L"
              pt: "VLP"
######### GABINET    #######################################
######### SYPIALNIA  #######################################
# S05_L S05_P S07_LG S07_LD S06_PG S06_PD
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S05_L
    remote_id: S05_L
    type: data
    on_multi_click:
      - timing:
          - ON for at least 3s
        then:
          - logger.log: "S05_L VLP -> Sypialnia wejscie lewa"
          - script.execute:
              id: sypialnia
              sn: "S05_L"
              pt: "VLP"
  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S05_P
    remote_id: S05_P
    type: data
    on_multi_click:
      - timing:
          - ON for at least 3s
        then:
          - logger.log: "S05_P VLP -> Sypialnia wejscie prawa"
          - script.execute:
              id: sypialnia
              sn: "S05_P"
              pt: "VLP"
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "S05_P LP -> Sypialnia wejscie prawa"
          - script.execute:
              id: sypialnia
              sn: "S05_P"
              pt: "LP"
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "S05_P SP -> Sypialnia wejscie prawa"
          - script.execute:
              id: sypialnia
              sn: "S12_P"
              pt: "SP"

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S06_PG
    remote_id: S06_PG
    type: data
    on_multi_click:
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "S06_PG LP -> Sypialnia prawa prawa gora"
          - script.execute:
              id: sypialnia
              sn: "S06_PG"
              pt: "LP"
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "S06_PG SP -> Sypialnia prawa prawa gora"
          - script.execute:
              id: sypialnia
              sn: "S06_PG"
              pt: "SP"

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S06_PD
    remote_id: S06_PD
    type: data
    on_multi_click:
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "S06_PD LP -> Sypialnia prawa prawa dol"
          - script.execute:
              id: sypialnia
              sn: "S06_PD"
              pt: "LP"
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "S06_PD SP -> Sypialnia prawa prawa dol"
          - script.execute:
              id: sypialnia
              sn: "S06_PD"
              pt: "SP"

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S07_LG
    remote_id: S07_LG
    type: data
    on_multi_click:
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "S07_LG LP -> Sypialnia lewa lewa gora"
          - script.execute:
              id: sypialnia
              sn: "S07_LG"
              pt: "LP"
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "S07_LG SP -> Sypialnia lewa lewa gora"
          - script.execute:
              id: sypialnia
              sn: "S07_LG"
              pt: "SP"

  - platform: packet_transport
    transport_id: transport
    provider: boneio-32-l-07-39d104
    id: remote_S07_LD
    remote_id: S07_LD
    type: data
    on_multi_click:
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "S07_LD LP -> Sypialnia lewa lewa dol"
          - script.execute:
              id: sypialnia
              sn: "S07_LD"
              pt: "LP"
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "S07_LD SP -> Sypialnia lewa lewa dol"
          - script.execute:
              id: sypialnia
              sn: "S07_LD"
              pt: "SP"
######### SYPIALNIA  #######################################

light:
  - platform: monochromatic
    output: chl01
    name: 'L03 - Blenda sypialnia'
    id: L03
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chl02
    name: 'L04 - Lozko sypialnia'
    id: L04
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chl03
    name: 'L11 - Gabinet polka'
    id: L11
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chl04
    name: 'L12 - Gabinet blenda'
    id: L12
    default_transition_length: 2s
    gamma_correct: 0

  - platform: monochromatic
    output: chr01
    name: 'L09A'
    id: L09A
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr02
    name: 'L09B'
    id: L09B
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr03
    name: 'L10A'
    id: L10A
    default_transition_length: 2s
    gamma_correct: 0
  - platform: monochromatic
    output: chr04
    name: 'L10B'
    id: L10B
    default_transition_length: 2s
    gamma_correct: 0

sensor:
  - platform: lm75
    id: boneIO_temp
    name: 'Temperature'
    update_interval: 30s
    entity_category: diagnostic
    on_value_range:
      - above: 70.0
        then:
          - switch.turn_on: buzzer
      - below: 70.0
        then:
          - switch.turn_off: buzzer

switch:
  - platform: gpio
    id: buzzer
    name: 'Buzzer'
    pin:
      pcf8574: pcf_inputs
      number: 0
      mode:
        output: true
      inverted: true