substitutions:
  name: boneio-32-l-07-73be28
  friendly_name: 'BoneIO ESP 32x10 Lights 73be28'
  serial_prefix: 'esp' #Don't change it.

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  name_add_mac_suffix: false
  project:
    name: boneio.32x10-lights
    version: '0.7'

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16

udp:

packet_transport:
  - id: transport
    platform: udp
    update_interval: 5s
    encryption: 'JAG_BONEIO1_KEY' #set it to yours shared secret key
    rolling_code_enable: true
    binary_sensors:
      - S02B_P #L01 & L02 Salon dl_02
      - S03B_P #L01 & L02 Salon dl_02
      - S05_P  #L03 & L04 Sypialnia dl_01
      - S06_PG #L03 & L04 Sypialnia dl_01
      - S06_PD #L03 & L04 Sypialnia dl_01
      - S07_LG #L03 & L04 Sypialnia dl_01
      - S07_LD #L03 & L04 Sypialnia dl_01
      - S08_P  #Lazienka  dl_02
      - S08_L  #Lazienka  dl_02
      - S09_G  #Lazienka  dl_02
      - S09_D  #Przedpokuj dl_01
      - S10    #Przedpokuj dl_01
      - S11_P  #Przedpokuj dl_01
      - S12_P  #Gabinet    dl_01
      - CO_1   #Przedpokuj dl_01
      - CO_2   #Przedpokuj dl_01
      - CZ     #All dl_01 & dl_02
    providers:
      - name: boneio-dr-8ch-03-30f8d8
        encryption: 'JAG_BONEIO2_KEY' #set it to yours shared secret key
      - name: boneio-dr-8ch-03-7c8500
        encryption: 'JAG_BONEIO3_KEY' #set it to yours shared secret key

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-32x10_lights_v0_7.yaml@latest
  import_full_config: true

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.7.1
    files: [
      'devices/buzzer.yaml',
      'devices/serial_no.yaml',
      'devices_v0_7/display.yaml',
      'devices_v0_7/i2c.yaml',
      'devices_v0_7-v0_9/ina219.yaml',
      'devices_v0_7-v0_9/lm75b.yaml',
      'devices_v0_7-v0_9/pcf.yaml',
      'boards/output/out01_02.yaml',
      'boards/output/out03_04.yaml',
      'boards/output/out05_06.yaml',
      'boards/output/out07_08.yaml',
      'boards/output/out09_10.yaml',
      'boards/output/out11_12.yaml',
      'boards/output/out13_14.yaml',
      'boards/output/out15_16.yaml',
      'boards/output/out17_18.yaml',
      'boards/output/out19_20.yaml',
      'boards/output/out21_22.yaml',
      'boards/output/out23_24.yaml',
      'boards/output/out25_26.yaml',
      'boards/output/out27_28.yaml',
      'boards/output/out29_30.yaml',
      'boards/output/out31_32.yaml',
      # 'devices_v0_7-v0_9/one_wire.yaml',
    ]

logger:
api:
  reboot_timeout: 0s
ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
  local: true
  version: 3

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw
    servers:
      - ntp1.tp.pl
      - ntp2.tp.pl
    on_time:
      seconds: 0
      minutes: 0
      hours: 23
      then:
        - logger.log: "Godzina 23:00"
        - light.turn_off: O01_A

script:
  - id: salon
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("salon", "%s %s", sn.c_str(), pt.c_str());
          id(O01_A).toggle().perform();
          id(O02_A).toggle().perform();
          id(O03_A).toggle().perform();

  - id: sypialnia
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("sypialnia", "%s %s", sn.c_str(), pt.c_str());
          id(O08).toggle().perform();

  - id: gabinet
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("gabinet", "%s %s", sn.c_str(), pt.c_str());
          id(O10).toggle().perform();

  - id: przedpokuj
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("przedpokuj", "%s %s", sn.c_str(), pt.c_str());

  - id: lazienka
    parameters:
      sn: string #switch name
      pt: string #push type
    then:
      - lambda: |-
          ESP_LOGI("lazienka", "%s %s", sn.c_str(), pt.c_str());
          id(O09).toggle().perform();

light:
  - platform: binary
    name: 'Salon/Wypoczynek A'
    output: out_01
    id: O01_A
  - platform: binary
    name: 'Salon/Wypoczynek B'
    output: out_02
    id: O01_B
  - platform: binary
    name: 'Salon/Jadalnia A'
    output: out_03
    id: O02_A
  - platform: binary
    name: 'Salon/Jadalnia B'
    output: out_04
    id: O02_B
  - platform: binary
    name: 'Salon/Kuchnia A'
    output: out_05
    id: O03_A
  - platform: binary
    name: 'Salon/Kuchnia B'
    output: out_06
    id: O03_B
  - platform: binary
    name: 'Oswietlenie elewacja pole'
    output: out_07
    id: O04
  - platform: binary
    name: 'Oswietlenie podbitka'
    output: out_08
    id: O05
  - platform: binary
    name: 'Gniazdo zewnetrzne podbitka pole'
    output: out_09
    id: GZ01
  - platform: binary
    name: '_nieuzywane_01'
    output: out_10
    id: dont_use_01
  - platform: binary
    name: 'Sypialnia lozko prawa'
    output: out_11
    id: O07
  - platform: binary
    name: 'Sypialnia lozko lewa'
    output: out_12
    id: O06
  - platform: binary
    name: 'Sypialnia glowne'
    output: out_13
    id: O08
  - platform: binary
    name: 'Lazienka glowne'
    output: out_14
    id: O09
  - platform: binary
    name: 'Ganinet glowne'
    output: out_15
    id: O10
  - platform: binary
    name: '_nieuzywane_02'
    output: out_16
    id: dont_use_02
  - platform: binary
    name: 'Oswietlenie wejscie elewacja'
    output: out_17
    id: O11
  - platform: binary
    name: 'Oswietlenie wejscie'
    output: out_18
    id: O12
  - platform: binary
    name: 'Gniazdo zewnetrzne zachod'
    output: out_19
    id: GZ02
  - platform: binary
    name: 'Gniazdo zewnetrzne elewacja wejscie'
    output: out_20
    id: GZ03
  - platform: binary
    name: '_nieuzywane_03'
    output: out_21
    id: dont_use_03
  - platform: binary
    name: '_nieuzywane_04'
    output: out_22
    id: dont_use_04
  - platform: binary
    name: '_nieuzywane_05'
    output: out_23
    id: dont_use_05
  - platform: binary
    name: '_nieuzywane_06'
    output: out_24
    id: dont_use_06
  - platform: binary
    name: '_nieuzywane_07'
    output: out_25
    id: dont_use_07
  - platform: binary
    name: '_nieuzywane_08'
    output: out_26
    id: dont_use_08
  - platform: binary
    name: '_nieuzywane_09'
    output: out_27
    id: dont_use_09
  - platform: binary
    name: '_nieuzywane_10'
    output: out_28
    id: dont_use_10
  - platform: binary
    name: '_nieuzywane_11'
    output: out_29
    id: dont_use_11
  - platform: binary
    name: '_nieuzywane_12'
    output: out_30
    id: dont_use_12
  - platform: binary
    name: '_nieuzywane_13'
    output: out_31
    id: dont_use_13
  - platform: binary
    name: '_nieuzywane_14'
    output: out_32
    id: dont_use_14

binary_sensor:
  - platform: gpio
    name: 'Salon przy oknie tarasowym - Prawa'
    id: S01_P
    pin:
      pcf8574: pcf_inputs_1to14
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S01_P OP -> Okno tarasowym - Prawa"

  - platform: gpio
    name: 'Salon przy oknie tarasowym - Lewa'
    id: S01_L
    pin:
      pcf8574: pcf_inputs_1to14
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S01_L OP -> Okno tarasowym - Prawa"

  - platform: gpio
    name: 'Salon przy wyspie A - Prawa'
    id: S02A_P
    pin:
      pcf8574: pcf_inputs_1to14
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S02A_P OP -> Przy wyspie A prawy"
        - script.execute:
            id: salon
            sn: "S02A_P"
            pt: "OP"

  - platform: gpio
    name: 'Salon przy wyspie A - Lewa'
    id: S02A_L
    pin:
      pcf8574: pcf_inputs_1to14
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S02A_L OP -> Przy wyspie A lewa"

  - platform: gpio
    name: 'Salon przy wyspie B - Prawa'
    id: S02B_P
    pin:
      pcf8574: pcf_inputs_1to14
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S02B_P OP -> Przy wyspie B prawa"

  - platform: gpio
    name: 'Salon przy wyspie B - Lewa'
    id: S02B_L
    pin:
      pcf8574: pcf_inputs_1to14
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S02B_L OP -> Przy wyspie B lewa"

  - platform: gpio
    name: 'Salon przy wejsciu A - Prawa'
    id: S03A_P
    pin:
      pcf8574: pcf_inputs_1to14
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S03A_P OP -> Przy wejsciu A prawy"
        - script.execute:
            id: salon
            sn: "S03A_P"
            pt: "OP"

  - platform: gpio
    name: 'Salon przy wejsciu A - Lewa'
    id: S03A_L
    pin:
      pcf8574: pcf_inputs_1to14
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S03A_L OP -> Przy wejsciu A lewa"

  - platform: gpio
    name: 'Salon przy wejsciu B - Prawa'
    id: S03B_P
    pin:
      pcf8574: pcf_inputs_1to14
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S03B_P OP -> Przy wejsciu B prawy"

  - platform: gpio
    name: 'Salon przy wejsciu B - Lewa'
    id: S03B_L
    pin:
      pcf8574: pcf_inputs_1to14
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S03B_P OP -> Przy wejsciu B lewa"

  - platform: gpio
    name: 'Sypialnia przy oknie tarasowym - Prawa'
    id: S04_P
    pin:
      pcf8574: pcf_inputs_1to14
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S04_P OP -> okno tarasowe prawa"

  - platform: gpio
    name: 'Sypialnia przy oknie tarasowym - Lewa'
    id: S04_L
    pin:
      pcf8574: pcf_inputs_1to14
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S04_L OP -> okno tarasowe lewa"

  - platform: gpio
    name: 'Sypialnia przy wejsciu - Prawa'
    id: S05_P
    pin:
      pcf8574: pcf_inputs_1to14
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S05_P OP -> Przy wejsciu - prawa"

  - platform: gpio
    name: 'Sypialnia przy wejsciu - Lewa'
    id: S05_L
    pin:
      pcf8574: pcf_inputs_1to14
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S05_L OP -> Przy wejsciu lewa"
        - script.execute:
            id: sypialnia
            sn: "S05_L"
            pt: "OP"

  - platform: gpio
    name: 'Sypialnia przy lozku po prawej - Prawa Dol'
    id: S06_PD
    pin:
      pcf8574: pcf_inputs_15to28
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S06_PD OP -> prawa prawa dol"

  - platform: gpio
    name: 'Sypialnia przy lozku po prawej - Prawa Gora'
    id: S06_PG
    pin:
      pcf8574: pcf_inputs_15to28
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S06_PG OP -> prawa prawa gora"

  - platform: gpio
    name: 'Sypialnia przy łużku po prawej - Lewa Dol'
    id: S06_LD
    pin:
      pcf8574: pcf_inputs_15to28
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S06_LD OP -> prawa lewa dol"

  - platform: gpio
    name: 'Sypialnia przy łużku po prawej - Lewa Gora'
    id: S06_LG
    pin:
      pcf8574: pcf_inputs_15to28
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S06_LG OP -> prawa lewa gora"

  - platform: gpio
    name: 'Sypialnia przy łużku po lewej - Prawa Dol'
    id: S07_PD
    pin:
      pcf8574: pcf_inputs_15to28
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S07_PD OP -> lewa prawa dol"

  - platform: gpio
    name: 'Sypialnia przy łużku po lewej - Prawa Gora'
    id: S07_PG
    pin:
      pcf8574: pcf_inputs_15to28
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S07_PG OP -> lewa prawa gora"

  - platform: gpio
    name: 'Sypialnia przy łużku po lewej - Lewa Dol'
    id: S07_LD
    pin:
      pcf8574: pcf_inputs_15to28
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S07_LD OP -> lewa lewa dol"

  - platform: gpio
    name: 'Sypialnia przy łużku po lewej - Lewa Gora'
    id: S07_LG
    pin:
      pcf8574: pcf_inputs_15to28
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S07_LG OP -> lewa lewa gora"

  - platform: gpio
    name: 'Lazienka przy lustrze - Prawa'
    id: S08_P
    pin:
      pcf8574: pcf_inputs_15to28
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S08_P OP -> lustro prawa"

  - platform: gpio
    name: 'Lazienka przy lustrze - Lewa'
    id: S08_L
    pin:
      pcf8574: pcf_inputs_15to28
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S08_L OP -> lustro lewa"

  - platform: gpio
    name: 'Wejscie do lazienki - Gora'
    id: S09_G
    pin:
      pcf8574: pcf_inputs_15to28
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S09_G OP -> Wejscie gora"
        - script.execute:
            id: lazienka
            sn: "S09_L"
            pt: "OP"

  - platform: gpio
    name: 'Wejscie do lazienki - Dol'
    id: S09_D
    pin:
      pcf8574: pcf_inputs_15to28
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S09_D OP -> Wejscie dol"

  - platform: gpio
    name: 'Przedpokuj wejscie do sypialni/salonu'
    id: S10
    pin:
      pcf8574: pcf_inputs_15to28
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S10 OP -> przedpokoj sypialnia/salon"

  - platform: gpio
    name: 'Przedpokuj wejscie do domu - Prawa'
    id: S11_P
    pin:
      pcf8574: pcf_inputs_15to28
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S11_P OP -> przedpokoj wejscie prawa"

  - platform: gpio
    name: 'Przedpokuj wejscie do domu - Lewa'
    id: S11_L
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S11_L OP -> przedpokoj wejscie lewa"

  - platform: gpio
    name: 'Gabinet - Prawa'
    id: S12_P
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S12_P OP -> gabinet prawa"

  - platform: gpio
    name: 'Gabinet - Lewa'
    id: S12_L
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "S12_L OP -> gabinet Lewa"
        - script.execute:
            id: gabinet
            sn: "S12_L"
            pt: "OP"

  - platform: gpio
    name: 'Czujnik obecnosci 1'
    id: CO_1
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "CO_1 OP -> czujnik obecnosci 1"

  - platform: gpio
    name: 'Czujnik obecnosci 2'
    id: CO_2
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - logger.log: "CO_2 OP -> czujnik obecnosci 2"

  - platform: gpio
    name: 'Czujnik zmierzchowy'
    id: CZ #IN_34
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 5
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on:
          seconds: 30
    on_press:
      then:
        - logger.log: "CZ OP -> czujnik zmierzchu"
        - if:
            condition:
              lambda: |-
                ESP_LOGI("in condition", "%s", "_1_");
                auto t = id(sntp_time).now();
                if (!t.is_valid()) {
                  ESP_LOGI("in condition", "%s", "_2_");
                  return false;
                }
                int h = t.hour;
                int m = t.minute;
                ESP_LOGI("in condition", "%s %d %d", "_3_", h, m);
                return (h >= 15 && h < 23);
            then:
              - light.turn_on: O01_A
    on_release:
      then:
        - logger.log: "CZ OR -> czujnik zmierzchu"
        - light.turn_off: O01_A

  - platform: gpio
    name: 'IN_35'
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 6
      mode:
        input: true
      inverted: true
######################
### MODBUS SECTION ###
######################
# UNCOMMENT BELOW TO USE MODBUS
# uart:
#   id: uart_pin14_15
#   rx_pin: GPIO14
#   tx_pin: GPIO15
#   baud_rate: 9600
#   stop_bits: 1

# modbus:
#   send_wait_time: 200ms
#   uart_id: uart_pin14_15
#   id: boneio_modbus

# modbus_controller:
#   - id: YOURDEVICE ID
#     address: 0x09
#     modbus_id: mod_bus
#     setup_priority: -10
#     update_interval: 60s