# https://shelly-api-docs.shelly.cloud/gen2/General/RPCChannels
# http://${SHELLY}/rpc/Switch.Set?id=0&on=true

### on
GET http://192.168.0.165/rpc/Switch.Set?id=0&on=true

### off
GET http://192.168.0.165/rpc/Switch.Set?id=0&on=false

### Get state
GET http://10.10.1.120/rpc/Switch.GetStatus?id=0

### Get state
GET http://10.10.1.63/rpc/Switch.GetStatus?id=0
